# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#

title: "John Winnett"
email: jawinnet@uwaterloo.ca
description: >- # this means to ignore newlines until "baseurl:"
  This is the personal website of a Data Science student at the University of Waterloo.
  Learn about my past and current coding projects, as well as a little about me.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://johnwin8.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  JohnWin8

theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
 exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - readme.md
